substitutions:
  board_name: "transit-board-a"
  friendly_name: "Transit Board"
  cta_api_key: ""  # Only include for local development, do not push to a public repository!
  github_repo: "seanalewine/transit-board"
  project_version: "dev" #Change to "dev" to deploy latest dev branch
  release_type: "dev" #Change to "dev" to deploy latest dev branch

packages:
  base: !include ../templates/base.yaml

esp32:
  variant: esp32c6
  framework:
    type: esp-idf
  cpu_frequency: 160MHz

esphome:
  includes:
    - ../templates/station_map.h

light:
  - platform: esp32_rmt_led_strip
    id: stop_indicators
    rgb_order: GRB
    pin: GPIO0
    internal: true
    default_transition_length: "500ms"
    use_psram: false
    num_leds: 320
    chipset: WS2812
    name: "Stop Indicators"
