wifi_ssid: "Your wifi name here" #Verify the network capabilities of your ESP32 microcontroller, you may need to use a 2.4ghz wifi network.
wifi_password: "password here"
transition_length: 0.25s #Set through trial and error
