# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Live Train Tracker Server for CTA
description: Tool for retrieving live train location data over CTA API and outputing an array of stations with trains due.
url: "https://github.com/seanalewine/cta-location-tracker/tree/main/tracker"
version: "0.1.2"
slug: tracker
init: false
ingress: false
map:
  - share:rw
  - media:rw
  - share:rw
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
   api_key: Provided by CTA Webmaster
   trainsPerLine: Not Working. Output up to 10 different train runs on each line
   website_name: CTA Live Tracker
   init_commands: []
schema:
   api_key: str
   trainsPerLine: str  
   website_name: str
   init_commands:
    - str?
ports:
   8000/tcp: 80
ports_description:
   8000/tcp: Web interface http
# image: "ghcr.io/home-assistant/{arch}-addon-example"   
