name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint ESPHome configs
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v5.0.0

      - name: Set up Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.11'

      - name: Install ESPHome
        run: pip install esphome

      - name: Validate ESPHome configurations
        run: |
          for config in esphome-controller/boards/*.yaml; do
            esphome config "$config" || exit 1
          done

      - name: Validate ESPHome template
        run: esphome config esphome-controller/templates/base.yaml